# Generated by Django 4.2.3 on 2023-08-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Salary', 'green'), ('Gift', 'purple'), ('Investment', 'lightblue'), ('Rewards', 'orange'), ('Other', 'lightgray')], default='Salary', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
            ],
        ),
    ]
