# Generated by Django 4.2.3 on 2023-08-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Clothing', 'hotpink'), ('Restaurant', 'red'), ('Supermarket', 'darkgreen'), ('Home', 'orange'), ('Travel', 'darkblue'), ('Transport', 'lightblue'), ('Other', 'lightgray')], default='Clothing', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
