# Generated by Django 4.2.3 on 2023-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_account_balance_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('home', 'Home'), ('travel', 'Travel'), ('transport', 'Transport'), ('other', 'Other')], default='clothing', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('gift', 'Gift'), ('investment', 'Investment'), ('rewards', 'Rewards'), ('other', 'Other')], default='salary', max_length=20),
        ),
    ]
