# Generated by Django 4.2.3 on 2023-08-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_budget_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='account',
        ),
    ]
