# Generated by Django 4.2.3 on 2023-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_budget_date_from_remove_budget_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('HSBC', 'HSBC'), ('Barclays', 'Barclays'), ('Lloyds', 'Lloyds'), ('NatWest', 'NatWest'), ('Santander', 'Santander'), ('TSB', 'TSB'), ('Nationwide', 'Nationwide'), ('Halifax', 'Halifax'), ('Metro-Bank', 'Metro-Bank')], default='HSBC', max_length=20),
        ),
    ]
